# Generated by Django 5.1.6 on 2025-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefield',
            name='name',
        ),
        migrations.AlterField(
            model_name='servicefield',
            name='value',
            field=models.CharField(max_length=350),
        ),
    ]
