# Generated by Django 5.1.6 on 2025-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finservice', '0003_consultationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='city_or_pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
